language: node_js

node_js:
  - "4.0.0"
  - "5.0.0"
  - "6.0.0"
  - "stable"

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

